name: Deploy website for test

on:
  push:
    branches:
      - 'develop-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install dependencies
        run: |
          composer install

      - name: Prod mod
        run: |
          mv .env.prod .env

      - name: Exports files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: .
          target: ~/www/dev
          rm: true

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: chmod -R 777 ~/www/dev/cache